version: '3.3'

services:
  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - ./volumes/db_data:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - 3201:8080
