name: PyLint Runner

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Pylint
        run: |
          pylint --rcfile=.pylintrc --disable=unused-argument,unused-import,unused-variable,wrong-import-order,wrong-import-position,import-outside-toplevel,global-statement,logging-fstring-interpolation **/*.py
          #TODO: need to double-check `disabled` before release
