name: PyTest Runner

on:
  workflow_dispatch:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run PyTest
        run: |
          export NO_DB=true
          py.test -v --cov=app tests/
